### ISSUE TITLE
"Download image" doesn't work in Safari

### ISSUE THREAD

**Issue by clarklab** [voxmedia/meme#6]
When trying to save an image in Safari, I (and other users in my office) get the following error:

SecurityError: DOM Exception 18: An attempt was made to break through the security policy of the user agent. saveCanvas

![meme-error](https://cloud.githubusercontent.com/assets/160409/3526150/a53e0e34-0779-11e4-8a88-1b58bc0ce454.png)

Any suggestions there? Is that just in my build? Things work just fine in Chrome.

**Comment by gmac** [comment]
The application no longer uses `saveCanvas` so this specific issue should be moot.

However, Safari is still a lot more finicky than Chrome. Safari doesn't support the `download` attribute, so I've added a note into the Safari display that instructs the user to "Right-click button and select 'Download Linked File...' to save image". That's the most robust FE-only download method I can think of for Safari at the moment, and worse case scenario – they click the button and get taken to their rendered image in a new browser window.
